clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 158.160.141.195
      ansible_connection: ssh
      ansible_user: lamer
      ansible_ssh_private_key_file: ssh_env/id_rsa_insecure_clickhouse-01

vector:
  hosts:
    clickhouse-02:
      ansible_host: 158.160.164.93
      ansible_connection: ssh
      ansible_user: lamer
      ansible_ssh_private_key_file: ssh_env/id_rsa_insecure_clickhouse-02
